### ISSUE TITLE
Have changed delimiters affect safe signal templates

### ISSUE THREAD

**Issue by neeasade** [Wilfred/mustache.el#14]
I'm using mustache.el to make an org-mode template -- org mode macros are invoked EG `{{{name(stuff)}}}`. When I change the delimeters in mustache.el, the `{{{` pairings are still caught:

``` emacs-lisp
(mustache-render "{{{a}}}"
  (ht ("a" "content")))

;; => "content"


(mustache-render "{{=<% %>=}} {{a}}"
  (ht ("a" "content")))

;; => " {{a}}"


(mustache-render "{{=<% %>=}} {{{a}}}"
  (ht ("a" "content")))

;; => " {{& a}}"
;; ! Expected: "{{{a}}}""



```

**Comment by Wilfred** [comment]
Yep, that's a bug IMO, and the spec doesn't seem to have an opinion on this.

Based on https://stackoverflow.com/a/39412783/509706 it looks like the triple curly syntax is also translated when you change delimiters. So the following are equivalent:

```
{{{a}}}
{{=<% %>=}}<%{a}%>
```
