### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by excalamus** [Wilfred/mustache.el#7]
I'm interested in using your library, but there is no explicit license given.  Therefore, all rights are reserved.  Would you be willing to release your library under a free license?

I'd be happy to assist you in setting up the appropriate notices.

Here is a list of free licenses: https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses

Popular licenses include [GPLv3](https://www.gnu.org/licenses/gpl-howto.html), [Apache 2.0](https://directory.fsf.org/wiki/License:Apache-2.0), the [Modified BSD](https://directory.fsf.org/wiki/License:BSD-3-Clause), and [X11 ("MIT license")](https://directory.fsf.org/wiki/License:X11).

**Comment by excalamus** [comment]
I see reference to GPLv3 in the headers of your programs.  Is this the intended license?  If so, I can help you get the COPYING file and other notices in place.

**Comment by Wilfred** [comment]
Yep, Emacs convention is to put the copyright in the file header.

If you'd like a COPYING file too I would accept a PR :)
